openapi: 3.0.0
info:
  title: Pokémon API
  version: 1.0.0
  description: A simple Pokémon API for listing and managing Pokémon data

servers:
  - url: https://api.example.com/v1
    description: Main API server

paths:
  /pokemon:
    get:
      summary: Get a list of Pokémon
      responses:
        '200':
          description: A list of Pokémon
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pokemon'
    post:
      summary: Add a new Pokémon
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewPokemon'
      responses:
        '201':
          description: Pokémon created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pokemon'

  /pokemon/{id}:
    get:
      summary: Get details of a specific Pokémon
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Pokémon details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pokemon'
        '404':
          description: Pokémon not found

components:
  schemas:
    Pokemon:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        type:
          type: string
        level:
          type: integer
        evolves_to:
          type: string
          nullable: true
    NewPokemon:
      type: object
      required:
        - name
        - type
        - level
      properties:
        name:
          type: string
        type:
          type: string
          example: fire
        level:
          type: integer
          minimum: 1
          maximum: 100
        evolves_to:
          type: string
          nullable: true
