openapi: 3.0.0
info:
  title: RAWG Video Game API
  version: 1.0.0
  description: Free video game database API (simplified version)

servers:
  - url: https://api.rawg.io/api

paths:
  /games:
    get:
      summary: Get a list of video games
      parameters:
        - name: page
          in: query
          schema:
            type: integer
          description: Page number
        - name: page_size
          in: query
          schema:
            type: integer
          description: Number of items per page
      responses:
        '200':
          description: A list of games
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/Game'

components:
  schemas:
    Game:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        released:
          type: string
        background_image:
          type: string
        rating:
          type: number
