name: API Specs Release
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get
        working-directory: ./scripts

      - name: Create releases directory
        run: mkdir -p releases

      - name: Process specs and create release
        run: dart run processor.dart
        working-directory: ./scripts
        env:
          GITHUB_RUN_ID: ${{ github.run_id }}

      - name: Get zip file name
        id: zipfile
        run: echo "name=api-specs-${{ github.run_id }}.zip" >> $GITHUB_OUTPUT

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: releases/${{ steps.zipfile.outputs.name }}
          tag_name: "v${{ github.run_id }}"
          name: "API Specs v${{ github.run_id }}"
          body: "Automated release of processed OpenAPI specifications"
          draft: false
          prerelease: false