name: YAML to JSON Processor

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  convert-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get
        working-directory: ./scripts

      - name: Ensure directories exist
        run: |
          mkdir -p sources
          mkdir -p releases

      - name: Run conversion
        run: dart run processor.dart
        working-directory: ./scripts

      - name: Generate tag name
        run: echo "TAG_NAME=release-$(" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: releases/final.zip
          tag_name: ${{ env.TAG_NAME }}
          name: "Final Conversion"
          draft: false
          prerelease: false