name: Convert YAML to JSON and Release
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  convert-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get
        working-directory: ./scripts

      - name: Create directories
        run: |
          mkdir -p generated
          mkdir -p releases

      - name: Run conversion script
        run: dart run processor.dart
        working-directory: ./scripts
        env:
          GITHUB_RUN_ID: ${{ github.run_id }}

      - name: Clean up old releases
        run: |
          # Keep only the last 5 releases
          ls -t releases/*.zip | tail -n +6 | xargs rm -f || true

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            generated/**/*.json
            releases/generated-json-${{ github.run_id }}.zip
          tag_name: "v${{ github.run_number }}"
          name: "JSON Conversion v${{ github.run_number }}"
          body: "Automated release of converted JSON files from YAML sources"
          draft: false
          prerelease: false
          generate_release_notes: true