name: Release Generated Folder
on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      # Generate your JSON files (keep your existing steps)
      - name: Generate JSON specs
        run: |
          dart pub get
          dart run processor.dart
        working-directory: ./scripts
        env:
          SOURCES_DIR: '../sources'
          OUTPUT_DIR: '../generated'

      # Create ZIP of ONLY the generated folder
      - name: Create ZIP package
        run: |
          TIMESTAMP=$(date +'%Y%m%d')
          
          # Create ZIP with clean structure (no parent folders)
          (cd generated && zip -r ../generated-$TIMESTAMP.zip .)
          
          # Move to release assets folder
          mkdir -p release_assets
          mv generated-$TIMESTAMP.zip release_assets/
          echo "ZIP_PATH=release_assets/generated-$TIMESTAMP.zip" >> $GITHUB_ENV

      # Create GitHub Release
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.ZIP_PATH }}
          tag_name: "generated-${{ env.TIMESTAMP }}"
          name: "Generated API Specs (${{ env.TIMESTAMP }})"
          body: "Automated release of processed API specifications"
          prerelease: false
