name: API Specs Processor
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  process_and_package:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get
        working-directory: ./scripts
      
      - name: Generate JSON specs
        run: dart run processor.dart
        working-directory: ./scripts
        env:
          SOURCES_DIR: '../sources'
          OUTPUT_DIR: '../generated'

      - name: Verify generated files exist
        run: |
          if [ ! -d "generated" ] || [ -z "$(ls -A generated)" ]; then
            echo "Error: No files were generated in the 'generated' directory"
            exit 1
          fi

      - name: Create clean ZIP package
        run: |
          mkdir -p packages
          TIMESTAMP=$(date +'%Y%m%d-%H%M%S')
          RELEASE_NAME="apis-$TIMESTAMP"
          
          # Create ZIP with proper structure
          (cd generated && zip -r ../packages/${RELEASE_NAME}.zip .)
          
          echo "ZIP created at packages/${RELEASE_NAME}.zip"
          echo "RELEASE_TAG=release-${TIMESTAMP%_*}" >> $GITHUB_ENV

      - name: Upload Release Asset
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          files: packages/*.zip
          tag_name: ${{ env.RELEASE_TAG }}
          prerelease: false
          generate_release_notes: true
