name: YAML to JSON Processor

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  convert-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get
        working-directory: ./scripts

      - name: Create directories
        run: |
          mkdir -p sources
          mkdir -p releases

      - name: Run conversion
        run: dart run processor.dart
        working-directory: ./scripts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: releases/final.zip
          tag_name: "release-$(date +%s)"
          name: "Final Conversion"
          draft: false
          prerelease: false