name: API Specs Processor
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  process_and_package:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get
        working-directory: ./scripts
      
      - name: Generate JSON specs
        run: dart run processor.dart
        working-directory: ./scripts
        env:
          SOURCES_DIR: '../sources'
          OUTPUT_DIR: '../generated'

      - name: Create clean ZIP package
        run: |
          # Create directories
          mkdir -p packages
          
          # Create timestamp-based filename
          RELEASE_NAME="apis-$(date +'%Y%m%d-%H%M%S')"
          
          # Create ZIP with clean structure
          cd generated
          zip -r ../packages/${RELEASE_NAME}.zip .
          
          echo "ZIP created at packages/${RELEASE_NAME}.zip"

      - name: Upload Release Asset
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          files: packages/*.zip
          tag_name: "release-$(date +'%Y%m%d')"
          prerelease: false
          generate_release_notes: true
