name: OpenAPI Processor

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get

      - name: Convert YAML to JSON
        run: dart run main.dart

      - name: Upload final.zip
        uses: actions/upload-artifact@v3
        with:
          name: final.zip
          path: releases/final.zip
          retention-days: 90