name: Release Generated Folder Only
on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Install Dart
        uses: dart-lang/setup-dart@v1
        with:
          version: '3.2.1'

      - name: Generate JSON specs
        run: |
          dart pub get
          dart run processor.dart
        working-directory: ./scripts
        env:
          SOURCES_DIR: '../sources'
          OUTPUT_DIR: '../generated'

      - name: Verify generated files
        run: |
          if [ ! -d "generated" ] || [ -z "$(ls -A generated)" ]; then
            echo "❌ Error: No files in generated directory"
            exit 1
          fi
          echo "✅ Generated files verified"

      - name: Create Clean ZIP
        run: |
          TIMESTAMP=$(date +'%Y%m%d-%H%M%S')
          
          # KEY FIX: Use '*/.' to only include contents
          (cd generated && zip -r ../generated-$TIMESTAMP.zip */.)
          
          # Debug output
          echo "ZIP contents:"
          unzip -l generated-$TIMESTAMP.zip
          
          mkdir -p release_assets
          mv generated-$TIMESTAMP.zip release_assets/
          echo "ZIP_PATH=release_assets/generated-$TIMESTAMP.zip" >> $GITHUB_ENV
          echo "RELEASE_TAG=generated-$TIMESTAMP" >> $GITHUB_ENV

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.ZIP_PATH }}
          tag_name: ${{ env.RELEASE_TAG }}
          name: "API Specs (${{ env.RELEASE_TAG }})"
          body: "Contains only the generated JSON files"
          prerelease: false
