name: Release Generated Folder
on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      # Proper Dart setup
      - name: Install Dart
        uses: dart-lang/setup-dart@v1
        with:
          version: '3.2.1'  # Specify your Dart version

      # Generate JSON files
      - name: Generate JSON specs
        run: |
          dart pub get
          dart run processor.dart
        working-directory: ./scripts
        env:
          SOURCES_DIR: '../sources'
          OUTPUT_DIR: '../generated'

      # Verify generated files exist
      - name: Check generated files
        run: |
          if [ ! -d "generated" ] || [ -z "$(ls -A generated)" ]; then
            echo "❌ Error: No files in generated directory"
            exit 1
          fi
          echo "✅ Generated files verified"

      # Create clean ZIP (only generated folder contents)
      - name: Create ZIP package
        run: |
          TIMESTAMP=$(date +'%Y%m%d-%H%M%S')
          
          # Create ZIP with proper structure
          (cd generated && zip -r ../generated-$TIMESTAMP.zip .)
          
          # Verify ZIP contents
          echo "ZIP contents:"
          unzip -l generated-$TIMESTAMP.zip
          
          # Prepare release asset
          mkdir -p release_assets
          mv generated-$TIMESTAMP.zip release_assets/
          echo "ZIP_PATH=release_assets/generated-$TIMESTAMP.zip" >> $GITHUB_ENV
          echo "RELEASE_TAG=generated-$TIMESTAMP" >> $GITHUB_ENV

      # Create GitHub Release
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.ZIP_PATH }}
          tag_name: ${{ env.RELEASE_TAG }}
          name: "Generated API Specs (${{ env.RELEASE_TAG }})"
          body: "Automated release containing only generated JSON files"
          prerelease: false
