name: OpenAPI YAML to JSON Processor

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  convert-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v3
        with:
          sdk: stable

      - name: Install dependencies
        run: |
          dart pub add openapi_spec archive path yaml
          dart pub get

      - name: Prepare directories
        run: |
          mkdir -p sources
          mkdir -p releases
          if [ -z "$(ls -A sources)" ]; then
            echo "Adding sample OpenAPI file"
            curl -o sources/petstore.yaml https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v3.0/petstore.yaml
          fi

      - name: Run conversion
        run: dart run main.dart

      - name: Verify output
        id: verify
        run: |
          echo "Checking releases folder:"
          ls -la releases/
          if [ -f "releases/final.zip" ]; then
            echo "valid=true" >> $GITHUB_OUTPUT
            echo "Zip contents:"
            unzip -l releases/final.zip
          else
            echo "No final.zip found!"
            exit 1
          fi

      - name: Generate timestamp
        if: steps.verify.outputs.valid == 'true'
        id: timestamp
        run: echo "tag=release-$(date +%Y%m%d-%H%M%S)" >> $GITHUB_OUTPUT

      - name: Create Release
        if: steps.verify.outputs.valid == 'true'
        uses: softprops/action-gh-release@v1
        with:
          files: releases/final.zip
          tag_name: ${{ steps.timestamp.outputs.tag }}
          name: "OpenAPI JSON Bundle"
          draft: false
          prerelease: false
          body: |
            Generated OpenAPI JSON bundle
            - Contains validated OpenAPI specs
            - Generated at: $(date)
