name: Release Generated Folder Only
on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      # Generate your JSON files
      - name: Generate JSON specs
        run: |
          dart pub get
          dart run processor.dart
        working-directory: ./scripts
        env:
          SOURCES_DIR: '../sources'
          OUTPUT_DIR: '../generated'

      # Create ZIP of ONLY the generated folder contents
      - name: Create Clean ZIP
        run: |
          # Create timestamp
          TIMESTAMP=$(date +'%Y%m%d-%H%M%S')
          
          # Create ZIP with PROPER structure
          cd generated
          zip -r ../generated-$TIMESTAMP.zip *
          cd ..
          
          # Verify ZIP contents (debugging)
          unzip -l generated-$TIMESTAMP.zip
          
          # Prepare release asset
          mkdir -p release_assets
          mv generated-$TIMESTAMP.zip release_assets/
          echo "ASSET_PATH=release_assets/generated-$TIMESTAMP.zip" >> $GITHUB_ENV
          echo "RELEASE_TAG=generated-$TIMESTAMP" >> $GITHUB_ENV

      # Create GitHub Release
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.ASSET_PATH }}
          tag_name: ${{ env.RELEASE_TAG }}
          name: "Generated API Specs (${{ env.RELEASE_TAG }})"
          body: "Contains only the generated JSON files"
          prerelease: false
