name: OpenAPI YAML to JSON Processor

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  convert-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dependencies
        run: |
          dart pub get

      - name: Ensure directory structure
        run: |
          mkdir -p sources
          mkdir -p releases
          # Add sample OpenAPI file if sources is empty
          if [ -z "$(ls -A sources)" ]; then
            echo "ℹ️ No files in sources directory, adding sample OpenAPI spec"
            curl -o sources/sample-openapi.yaml https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v3.0/petstore.yaml
          fi

      - name: Run OpenAPI validation and conversion
        run: dart run main.dart
        env:
          VALIDATE_OPENAPI: "true"

      - name: Verify output
        run: |
          echo "Generated files:"
          ls -lh releases/
          unzip -l releases/final.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: releases/final.zip
          tag_name: final-$(date +%Y%m%d%H%M%S)
          name: "OpenAPI JSON Bundle"
          draft: false
          prerelease: false
          body: |
            Auto-generated OpenAPI JSON bundle
            Contains validated OpenAPI specifications converted to JSON format
            Generated at: $(date)