name: Create Release
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Daily

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        
      - name: Create ZIP
        run: dart run scripts/make_release.dart
        
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: releases/latest.zip
          tag_name: "v$(date +'%Y.%m.%d')"